resources:
  - manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/aclerici38/pocket-id-operator
    newName: ghcr.io/aclerici38/pocket-id-operator
    newTag: v0.5.0@sha256:23993896c6460972223123d7a5dd00dd97139960ac5166c0850723b2828c8168