---
# yaml-language-server: $schema=../dist/chart/values.schema.json
instance:
  spec:
    encryptionKey:
      value: "test-key-16chars"

users:
  - name: test-user-1
  - name: test-user-2
    spec:
      admin: true

userGroups:
  - name: test-group
    spec:
      users:
        userRefs:
          - name: test-user-1
          - name: test-user-2
