//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeySpec) DeepCopyInto(out *APIKeySpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeySpec.
func (in *APIKeySpec) DeepCopy() *APIKeySpec {
	if in == nil {
		return nil
	}
	out := new(APIKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyStatus) DeepCopyInto(out *APIKeyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyStatus.
func (in *APIKeyStatus) DeepCopy() *APIKeyStatus {
	if in == nil {
		return nil
	}
	out := new(APIKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomClaim) DeepCopyInto(out *CustomClaim) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomClaim.
func (in *CustomClaim) DeepCopy() *CustomClaim {
	if in == nil {
		return nil
	}
	out := new(CustomClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailNotificationsConfig) DeepCopyInto(out *EmailNotificationsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailNotificationsConfig.
func (in *EmailNotificationsConfig) DeepCopy() *EmailNotificationsConfig {
	if in == nil {
		return nil
	}
	out := new(EmailNotificationsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoIPConfig) DeepCopyInto(out *GeoIPConfig) {
	*out = *in
	if in.MaxmindLicenseKey != nil {
		in, out := &in.MaxmindLicenseKey, &out.MaxmindLicenseKey
		*out = new(SensitiveValue)
		(*in).DeepCopyInto(*out)
	}
	if in.DBURL != nil {
		in, out := &in.DBURL, &out.DBURL
		*out = new(SensitiveValue)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoIPConfig.
func (in *GeoIPConfig) DeepCopy() *GeoIPConfig {
	if in == nil {
		return nil
	}
	out := new(GeoIPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteConfig) DeepCopyInto(out *HTTPRouteConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ParentRefs != nil {
		in, out := &in.ParentRefs, &out.ParentRefs
		*out = make([]apisv1.ParentReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]apisv1.Hostname, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteConfig.
func (in *HTTPRouteConfig) DeepCopy() *HTTPRouteConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPAttributeMappingConfig) DeepCopyInto(out *LDAPAttributeMappingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPAttributeMappingConfig.
func (in *LDAPAttributeMappingConfig) DeepCopy() *LDAPAttributeMappingConfig {
	if in == nil {
		return nil
	}
	out := new(LDAPAttributeMappingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPConfig) DeepCopyInto(out *LDAPConfig) {
	*out = *in
	in.BindPassword.DeepCopyInto(&out.BindPassword)
	if in.AttributeMapping != nil {
		in, out := &in.AttributeMapping, &out.AttributeMapping
		*out = new(LDAPAttributeMappingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPConfig.
func (in *LDAPConfig) DeepCopy() *LDAPConfig {
	if in == nil {
		return nil
	}
	out := new(LDAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfig) DeepCopyInto(out *MetricsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfig.
func (in *MetricsConfig) DeepCopy() *MetricsConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedOIDCClientReference) DeepCopyInto(out *NamespacedOIDCClientReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedOIDCClientReference.
func (in *NamespacedOIDCClientReference) DeepCopy() *NamespacedOIDCClientReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedOIDCClientReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedUserGroupReference) DeepCopyInto(out *NamespacedUserGroupReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedUserGroupReference.
func (in *NamespacedUserGroupReference) DeepCopy() *NamespacedUserGroupReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedUserGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedUserReference) DeepCopyInto(out *NamespacedUserReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedUserReference.
func (in *NamespacedUserReference) DeepCopy() *NamespacedUserReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedUserReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCClientFederatedIdentity) DeepCopyInto(out *OIDCClientFederatedIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCClientFederatedIdentity.
func (in *OIDCClientFederatedIdentity) DeepCopy() *OIDCClientFederatedIdentity {
	if in == nil {
		return nil
	}
	out := new(OIDCClientFederatedIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCClientLogoSpec) DeepCopyInto(out *OIDCClientLogoSpec) {
	*out = *in
	if in.AutoGenerate != nil {
		in, out := &in.AutoGenerate, &out.AutoGenerate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCClientLogoSpec.
func (in *OIDCClientLogoSpec) DeepCopy() *OIDCClientLogoSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCClientLogoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCClientSecretKeys) DeepCopyInto(out *OIDCClientSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCClientSecretKeys.
func (in *OIDCClientSecretKeys) DeepCopy() *OIDCClientSecretKeys {
	if in == nil {
		return nil
	}
	out := new(OIDCClientSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCClientSecretSpec) DeepCopyInto(out *OIDCClientSecretSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = new(OIDCClientSecretKeys)
		**out = **in
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCClientSecretSpec.
func (in *OIDCClientSecretSpec) DeepCopy() *OIDCClientSecretSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCClientSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenceConfig) DeepCopyInto(out *PersistenceConfig) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenceConfig.
func (in *PersistenceConfig) DeepCopy() *PersistenceConfig {
	if in == nil {
		return nil
	}
	out := new(PersistenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDInstance) DeepCopyInto(out *PocketIDInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDInstance.
func (in *PocketIDInstance) DeepCopy() *PocketIDInstance {
	if in == nil {
		return nil
	}
	out := new(PocketIDInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDInstanceList) DeepCopyInto(out *PocketIDInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PocketIDInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDInstanceList.
func (in *PocketIDInstanceList) DeepCopy() *PocketIDInstanceList {
	if in == nil {
		return nil
	}
	out := new(PocketIDInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDInstanceSpec) DeepCopyInto(out *PocketIDInstanceSpec) {
	*out = *in
	in.EncryptionKey.DeepCopyInto(&out.EncryptionKey)
	if in.DatabaseUrl != nil {
		in, out := &in.DatabaseUrl, &out.DatabaseUrl
		*out = new(SensitiveValue)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Persistence.DeepCopyInto(&out.Persistence)
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.HostUsers != nil {
		in, out := &in.HostUsers, &out.HostUsers
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsConfig)
		**out = **in
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(HTTPRouteConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Config)
		(*in).DeepCopyInto(*out)
	}
	if in.SMTP != nil {
		in, out := &in.SMTP, &out.SMTP
		*out = new(SMTPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EmailNotifications != nil {
		in, out := &in.EmailNotifications, &out.EmailNotifications
		*out = new(EmailNotificationsConfig)
		**out = **in
	}
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(LDAPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		**out = **in
	}
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(TracingConfig)
		**out = **in
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(UIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UserManagement != nil {
		in, out := &in.UserManagement, &out.UserManagement
		*out = new(UserManagementConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GeoIP != nil {
		in, out := &in.GeoIP, &out.GeoIP
		*out = new(GeoIPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AuditLogRetentionDays != nil {
		in, out := &in.AuditLogRetentionDays, &out.AuditLogRetentionDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDInstanceSpec.
func (in *PocketIDInstanceSpec) DeepCopy() *PocketIDInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(PocketIDInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDInstanceStatus) DeepCopyInto(out *PocketIDInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDInstanceStatus.
func (in *PocketIDInstanceStatus) DeepCopy() *PocketIDInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(PocketIDInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDOIDCClient) DeepCopyInto(out *PocketIDOIDCClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDOIDCClient.
func (in *PocketIDOIDCClient) DeepCopy() *PocketIDOIDCClient {
	if in == nil {
		return nil
	}
	out := new(PocketIDOIDCClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDOIDCClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDOIDCClientList) DeepCopyInto(out *PocketIDOIDCClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PocketIDOIDCClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDOIDCClientList.
func (in *PocketIDOIDCClientList) DeepCopy() *PocketIDOIDCClientList {
	if in == nil {
		return nil
	}
	out := new(PocketIDOIDCClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDOIDCClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDOIDCClientSpec) DeepCopyInto(out *PocketIDOIDCClientSpec) {
	*out = *in
	if in.InstanceSelector != nil {
		in, out := &in.InstanceSelector, &out.InstanceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CallbackURLs != nil {
		in, out := &in.CallbackURLs, &out.CallbackURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogoutCallbackURLs != nil {
		in, out := &in.LogoutCallbackURLs, &out.LogoutCallbackURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(OIDCClientLogoSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.FederatedIdentities != nil {
		in, out := &in.FederatedIdentities, &out.FederatedIdentities
		*out = make([]OIDCClientFederatedIdentity, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUserGroups != nil {
		in, out := &in.AllowedUserGroups, &out.AllowedUserGroups
		*out = make([]NamespacedUserGroupReference, len(*in))
		copy(*out, *in)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(OIDCClientSecretSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SCIM != nil {
		in, out := &in.SCIM, &out.SCIM
		*out = new(SCIMSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDOIDCClientSpec.
func (in *PocketIDOIDCClientSpec) DeepCopy() *PocketIDOIDCClientSpec {
	if in == nil {
		return nil
	}
	out := new(PocketIDOIDCClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDOIDCClientStatus) DeepCopyInto(out *PocketIDOIDCClientStatus) {
	*out = *in
	if in.CallbackURLs != nil {
		in, out := &in.CallbackURLs, &out.CallbackURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogoutCallbackURLs != nil {
		in, out := &in.LogoutCallbackURLs, &out.LogoutCallbackURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUserGroupIDs != nil {
		in, out := &in.AllowedUserGroupIDs, &out.AllowedUserGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogoReachable != nil {
		in, out := &in.LogoReachable, &out.LogoReachable
		*out = new(bool)
		**out = **in
	}
	if in.DarkLogoReachable != nil {
		in, out := &in.DarkLogoReachable, &out.DarkLogoReachable
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDOIDCClientStatus.
func (in *PocketIDOIDCClientStatus) DeepCopy() *PocketIDOIDCClientStatus {
	if in == nil {
		return nil
	}
	out := new(PocketIDOIDCClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUser) DeepCopyInto(out *PocketIDUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUser.
func (in *PocketIDUser) DeepCopy() *PocketIDUser {
	if in == nil {
		return nil
	}
	out := new(PocketIDUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserGroup) DeepCopyInto(out *PocketIDUserGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserGroup.
func (in *PocketIDUserGroup) DeepCopy() *PocketIDUserGroup {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDUserGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserGroupList) DeepCopyInto(out *PocketIDUserGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PocketIDUserGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserGroupList.
func (in *PocketIDUserGroupList) DeepCopy() *PocketIDUserGroupList {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDUserGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserGroupSpec) DeepCopyInto(out *PocketIDUserGroupSpec) {
	*out = *in
	if in.InstanceSelector != nil {
		in, out := &in.InstanceSelector, &out.InstanceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomClaims != nil {
		in, out := &in.CustomClaims, &out.CustomClaims
		*out = make([]CustomClaim, len(*in))
		copy(*out, *in)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = new(UserGroupUsers)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedOIDCClients != nil {
		in, out := &in.AllowedOIDCClients, &out.AllowedOIDCClients
		*out = make([]NamespacedOIDCClientReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserGroupSpec.
func (in *PocketIDUserGroupSpec) DeepCopy() *PocketIDUserGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserGroupStatus) DeepCopyInto(out *PocketIDUserGroupStatus) {
	*out = *in
	if in.ManagedUserIDs != nil {
		in, out := &in.ManagedUserIDs, &out.ManagedUserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CustomClaims != nil {
		in, out := &in.CustomClaims, &out.CustomClaims
		*out = make([]CustomClaim, len(*in))
		copy(*out, *in)
	}
	if in.AllowedOIDCClientIDs != nil {
		in, out := &in.AllowedOIDCClientIDs, &out.AllowedOIDCClientIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserGroupStatus.
func (in *PocketIDUserGroupStatus) DeepCopy() *PocketIDUserGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserList) DeepCopyInto(out *PocketIDUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PocketIDUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserList.
func (in *PocketIDUserList) DeepCopy() *PocketIDUserList {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserSpec) DeepCopyInto(out *PocketIDUserSpec) {
	*out = *in
	in.Username.DeepCopyInto(&out.Username)
	in.FirstName.DeepCopyInto(&out.FirstName)
	in.LastName.DeepCopyInto(&out.LastName)
	in.Email.DeepCopyInto(&out.Email)
	in.DisplayName.DeepCopyInto(&out.DisplayName)
	if in.InstanceSelector != nil {
		in, out := &in.InstanceSelector, &out.InstanceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UserInfoSecretRef != nil {
		in, out := &in.UserInfoSecretRef, &out.UserInfoSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.APIKeys != nil {
		in, out := &in.APIKeys, &out.APIKeys
		*out = make([]APIKeySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserSpec.
func (in *PocketIDUserSpec) DeepCopy() *PocketIDUserSpec {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserStatus) DeepCopyInto(out *PocketIDUserStatus) {
	*out = *in
	if in.APIKeys != nil {
		in, out := &in.APIKeys, &out.APIKeys
		*out = make([]APIKeyStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserStatus.
func (in *PocketIDUserStatus) DeepCopy() *PocketIDUserStatus {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Config) DeepCopyInto(out *S3Config) {
	*out = *in
	in.AccessKeyID.DeepCopyInto(&out.AccessKeyID)
	in.SecretAccessKey.DeepCopyInto(&out.SecretAccessKey)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Config.
func (in *S3Config) DeepCopy() *S3Config {
	if in == nil {
		return nil
	}
	out := new(S3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCIMSpec) DeepCopyInto(out *SCIMSpec) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCIMSpec.
func (in *SCIMSpec) DeepCopy() *SCIMSpec {
	if in == nil {
		return nil
	}
	out := new(SCIMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMTPConfig) DeepCopyInto(out *SMTPConfig) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(SensitiveValue)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMTPConfig.
func (in *SMTPConfig) DeepCopy() *SMTPConfig {
	if in == nil {
		return nil
	}
	out := new(SMTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SensitiveValue) DeepCopyInto(out *SensitiveValue) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(v1.EnvVarSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SensitiveValue.
func (in *SensitiveValue) DeepCopy() *SensitiveValue {
	if in == nil {
		return nil
	}
	out := new(SensitiveValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringValue) DeepCopyInto(out *StringValue) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringValue.
func (in *StringValue) DeepCopy() *StringValue {
	if in == nil {
		return nil
	}
	out := new(StringValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIConfig) DeepCopyInto(out *UIConfig) {
	*out = *in
	if in.SessionDuration != nil {
		in, out := &in.SessionDuration, &out.SessionDuration
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIConfig.
func (in *UIConfig) DeepCopy() *UIConfig {
	if in == nil {
		return nil
	}
	out := new(UIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGroupUsers) DeepCopyInto(out *UserGroupUsers) {
	*out = *in
	if in.UserRefs != nil {
		in, out := &in.UserRefs, &out.UserRefs
		*out = make([]NamespacedUserReference, len(*in))
		copy(*out, *in)
	}
	if in.Usernames != nil {
		in, out := &in.Usernames, &out.Usernames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UserIDs != nil {
		in, out := &in.UserIDs, &out.UserIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupUsers.
func (in *UserGroupUsers) DeepCopy() *UserGroupUsers {
	if in == nil {
		return nil
	}
	out := new(UserGroupUsers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserManagementConfig) DeepCopyInto(out *UserManagementConfig) {
	*out = *in
	if in.AllowOwnAccountEdit != nil {
		in, out := &in.AllowOwnAccountEdit, &out.AllowOwnAccountEdit
		*out = new(bool)
		**out = **in
	}
	if in.SignupDefaultUserGroupIDs != nil {
		in, out := &in.SignupDefaultUserGroupIDs, &out.SignupDefaultUserGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserManagementConfig.
func (in *UserManagementConfig) DeepCopy() *UserManagementConfig {
	if in == nil {
		return nil
	}
	out := new(UserManagementConfig)
	in.DeepCopyInto(out)
	return out
}
