[changelog]
header = ""
body = """
{%- for group, commits in commits | group_by(attribute="group") %}
{%- for commit in commits %}
- kind: {{ group }}
  description: "{% if commit.scope %}({{ commit.scope }}) {% endif %}{{ commit.message | replace(from='"', to='\\"') }}"
{%- endfor %}
{%- endfor %}

"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false

commit_parsers = [
  { message = "^feat", group = "added" },
  { message = "^fix", group = "fixed" },
  { message = "^refactor", group = "changed" },
  { message = "^docs", group = "changed" },
  { message = "^chore", group = "changed" },
  { message = "\\(deps\\)", group = "changed" },
]

protect_breaking_commits = false
filter_commits = true
tag_pattern = "v[0-9].*"
topo_order = false
sort_commits = "oldest"
